### ISSUE TITLE
Filters make "AND" queries, not "OR"

### ISSUE THREAD

**Issue by peitalin** [TreasureProject/treasure-marketplace-subgraph#46]
### Describe the bug

Not sure if this is a bug, but when you select multiple filters the search query tries to filter using "AND" instead of "OR".

E.g. If I select `pink` and `light_orange` the search query tries to filter for smolBrains that have both (although none exist)
![image](https://user-images.githubusercontent.com/4037878/147902039-f53da7a4-50f4-42d3-8fc9-dc8d7c61de20.png)

On OpenSea the filters act as "OR" filters
![image](https://user-images.githubusercontent.com/4037878/147902146-ddbdae4b-cbb8-4348-b45b-cb4690072ae0.png)

Most attributes on the market are mutually exclusive (headsize, backgroundColor, etc), so switching to "OR" filters may improve UX a bit.
The flipside is, there may be future cases where a collection may have have multiple non-mutually exclusive attributes? 

The GraphQL query to the backend in `getCollectionListings` has something like
`$filter: ["Body,pink", "Body,light_orange"]`

### Steps to reproduce

Click on 2 or more filters for an attribute. E.g. click `pink` and `light_orange` background attribute filters.

### Expected behavior

As a user, I expect to see both `pink` and `light_orange` monkeys

### Platform

- OS: [e.g. macOS, Windows, Linux, iOS, Android]
- Browser: [e.g. Chrome, Safari, Firefox, React Native]
- Version: [e.g. 91.1]

**Comment by wyze** [comment]
So we use the graph. They currently don't support this, and their recommendation has been to split query into X amount of queries one for each filter, then combine the results. That's really not great, so this is kind of on the back burner until we come up with a better solution.

**Comment by wyze** [comment]
I am wondering if we can use Full Text Search here and get around it, would love to try it out on dev graph and see what kind of results we get. Could be something.

https://thegraph.com/docs/en/developer/create-subgraph-hosted#defining-fulltext-search-fields

**Comment by wyze** [comment]
@peitalin This should be much better with the latest marketplace update!

**Comment by peitalin** [comment]
Oh damn, congrats guys this is awesome.
Browsing on the marketplace for treasures + filters feels really good now.
